debug = false

logLevel = "DEBUG"

defaultEntryPoints = ["http", "https"]


[web]
address = ":8080"
  [web.auth.basic]
  users = ["admin:$apr1$TnfIqDkc$TnjA6SivljaG1N3avymft1"]


[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
      certFile = "/certs/traefik.crt"
      keyFile = "/certs/traefik.key"


# API definition
[api]
entryPoint = "traefik"
dashboard = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
swarmmode = true